# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Donnovan Feuillastre
title: Game Programmer
email: donnovan42320@gmail.com
location: France
#website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  PhantomDO
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: donnovan-feuillastre
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: France
#   icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Donnovan and I'm a programmer who loves to solves systemics problems inside a project to push it further. 
  I also have an interest in Game and Level Design, always eager to engage in discussions!

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        company: PIECE OF CAKE STUDIOS
        link: www.pieceofcake-studios.com
        job_title: Engine Programmer
        dates: Mai 2022 - March 2024
        quote: >
          Reference: **[Xavier Lemaitre](https://www.linkedin.com/in/xlemaitre/)**, CTO, PIECE OF CAKE STUDIOS
        description: | # this will include new lines to allow paragraphs
          - **Contributed to [Fantastic Haven](https://store.steampowered.com/app/2556470/Fantastic_Haven/)**: Implemented new gameplay systems and optimized the game. 
          - **Porting [My Fantastic Ranch](https://store.steampowered.com/app/1949100/My_Fantastic_Ranch_Unicorns__Dragons/) & [Hacktag](https://store.steampowered.com/app/622770/Hacktag/?curator_clanid=35988148)**: Integrated SDK features for Switch, PS4, PS5, and Xbox. 
          - **Debugging & QA**: Debugged and fixed issues reported by QA testers to ensure a smooth gameplay experience. 
          - **Development Assistance**: Assisted in the development of tools and plugins to streamline the game development process.
      - layout: left
        company: ICONIK STUDIO
        link: iconik.com
        job_title: Gameplay Programmer
        dates: April 2020 - August 2021
        quote: >
          Reference: **[Curtis Pelissier](https://www.linkedin.com/in/curtis-pelissier/)**, Generalist Programmer, ICONIK STUDIO
        description: | # this will include new lines to allow paragraphs
          - **[KINGPONG](https://store.steampowered.com/app/1501390/KING_PONG/)**: Implemented new enemy AI behavior and integrated new gameplay systems. 
          - **AI Customization Tools**: Developed tools for AI behavior customization using visual scripting (Behavior Tree). 
          - **Performance Optimization**: Optimized game performance for Meta Quest 1 & 2.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        name: UNIVERSITE LYON II
        dates: 2021 - 2022
        qualification: Master in Computer Science / Video Game Engineering (GAMAGORA)
        link: icom.univ-lyon2.fr/formation/master-2-informatique-gamagora-1
        #quote: >
        #  Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          Being able to handle all the programming tasks required to develop a video game, both for the game itself and for the software tools needed. Internship with Piece of Cake Studios (5 months).
      - layout: left
        name: CNAM SAINT-ETIENNE
        dates: 2020 - 2021
        qualification: Bachelor in Computer Science
        link: cnam-auvergnerhonealpes.com/licence-generale-informatique-g02501
        #quote: >
        #  Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          Being able to handle programming tasks required to develop software. Work-study with Iconik Studio (1 year).
      - layout: left
        name: IUT LE PUY EN VELAY
        dates: 2018 - 2020
        qualification: DUT in Computer Science
        link: www.uca.fr/formation/nos-formations/par-ufr-ecoles-et-iut/iut-clermont-auvergne/but/but-informatique-le-puy
        #quote: >
        #  Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          Being able to design and develop 2D and 3D software by acquiring skills in programming and image synthesis using languages and libraries such as C++, C#, Open GL and Unity. Internship with Iconik Studio (3 months).
      - layout: left
        name: BELLECOUR ECOLE
        dates: 2015 – 2018
        qualification: Bachelor in Game Design
        link: www.bellecour.fr/formation/bachelor-game-development
        #quote: >
        #  Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          Being able to make Game/Level Design documents and prototype games and levels with Unity 5 and Unreal Engine 4.


  - title: Skills # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Software & Tools
        description: | # this will include new lines to allow paragraphs
          C#, C/C++, Perforce, Git, Unity, Visual Studio, RenderDoc, Bash
      - layout: left
        title: Video Game Specific
        description: | # this will include new lines to allow paragraphs
          Gameplay Systems, Debugging Games, Cross-Platform Development, Performance Optimization, Virtual Reality, Game Design Principles
      - layout: left
        title: Soft Skills
        description: | # this will include new lines to allow paragraphs
          Problem solving, Synthesis, Teamwork, Reliable, Curious

  - title: Languages
    layout: text
    content: | # this will include new lines to allow paragraphs
      - **French**: Native
      - **English**: Fluent (Linguaskill C1)

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
